export {NavBar} from './navBar/index'
export { HeaderComponent } from './header/index'
export { AnimatedText } from './textoAnimado/index'
export { Fondo } from './fondo/index'
export {Diapositiva} from './diapositiva/index'